package com.vmware.avi.vro.model;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.vmware.o11n.plugin.sdk.annotation.VsoFinder;
import com.vmware.o11n.plugin.sdk.annotation.VsoMethod;
import com.vmware.o11n.plugin.sdk.annotation.VsoObject;
import com.vmware.avi.vro.Constants;
import org.springframework.stereotype.Service;

/**
 * The SeGroupAnalyticsPolicy is a POJO class extends AviRestResource that used for creating
 * SeGroupAnalyticsPolicy.
 *
 * @version 1.0
 * @since 
 *
 */
@VsoObject(create = false, name = "SeGroupAnalyticsPolicy")
@VsoFinder(name = Constants.FINDER_VRO_SEGROUPANALYTICSPOLICY)
@JsonIgnoreProperties(ignoreUnknown = true)
@Service
public class SeGroupAnalyticsPolicy extends AviRestResource {
    @JsonProperty("metrics_event_thresholds")
    @JsonInclude(Include.NON_NULL)
    private List<MetricsEventThreshold> metricsEventThresholds = null;



  /**
   * This is the getter method this will return the attribute value.
   * Thresholds for various events generated by metrics system.
   * Field introduced in 20.1.3.
   * Default value when not specified in API or module is interpreted by Avi Controller as null.
   * @return metricsEventThresholds
   */
  @VsoMethod
  public List<MetricsEventThreshold> getMetricsEventThresholds() {
    return metricsEventThresholds;
  }

  /**
   * This is the setter method. this will set the metricsEventThresholds
   * Thresholds for various events generated by metrics system.
   * Field introduced in 20.1.3.
   * Default value when not specified in API or module is interpreted by Avi Controller as null.
   * @return metricsEventThresholds
   */
  @VsoMethod
  public void setMetricsEventThresholds(List<MetricsEventThreshold>  metricsEventThresholds) {
    this.metricsEventThresholds = metricsEventThresholds;
  }

  /**
   * This is the setter method this will set the metricsEventThresholds
   * Thresholds for various events generated by metrics system.
   * Field introduced in 20.1.3.
   * Default value when not specified in API or module is interpreted by Avi Controller as null.
   * @return metricsEventThresholds
   */
  @VsoMethod
  public SeGroupAnalyticsPolicy addMetricsEventThresholdsItem(MetricsEventThreshold metricsEventThresholdsItem) {
    if (this.metricsEventThresholds == null) {
      this.metricsEventThresholds = new ArrayList<MetricsEventThreshold>();
    }
    this.metricsEventThresholds.add(metricsEventThresholdsItem);
    return this;
  }




@Override
public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
  SeGroupAnalyticsPolicy objSeGroupAnalyticsPolicy = (SeGroupAnalyticsPolicy) o;
  return   Objects.equals(this.metricsEventThresholds, objSeGroupAnalyticsPolicy.metricsEventThresholds);
}

@Override
public String toString() {
  StringBuilder sb = new StringBuilder();
  sb.append("class SeGroupAnalyticsPolicy {\n");
      sb.append("    metricsEventThresholds: ").append(toIndentedString(metricsEventThresholds)).append("\n");
      sb.append("}");
  return sb.toString();
}

/**
* Convert the given object to string with each line indented by 4 spaces
* (except the first line).
*/
private String toIndentedString(java.lang.Object o) {
  if (o == null) {
    return "null";
  }
  return o.toString().replace("\n", "\n    ");
}
}

