package com.vmware.avi.vro.model;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.vmware.o11n.plugin.sdk.annotation.VsoFinder;
import com.vmware.o11n.plugin.sdk.annotation.VsoMethod;
import com.vmware.o11n.plugin.sdk.annotation.VsoObject;
import com.vmware.avi.vro.Constants;
import org.springframework.stereotype.Service;

/**
 * The WafWhitelistLog is a POJO class extends AviRestResource that used for creating
 * WafWhitelistLog.
 *
 * @version 1.0
 * @since 
 *
 */
@VsoObject(create = false, name = "WafWhitelistLog")
@VsoFinder(name = Constants.FINDER_VRO_WAFWHITELISTLOG)
@JsonIgnoreProperties(ignoreUnknown = true)
@Service
public class WafWhitelistLog extends AviRestResource {
  @JsonProperty("actions")
  @JsonInclude(Include.NON_NULL)
  private List<String> actions = null;

  @JsonProperty("rule_name")
  @JsonInclude(Include.NON_NULL)
  private String ruleName = null;



  /**
   * This is the getter method this will return the attribute value.
   * Actions generated by this rule.
   * Enum options - WAF_POLICY_WHITELIST_ACTION_ALLOW, WAF_POLICY_WHITELIST_ACTION_DETECTION_MODE, WAF_POLICY_WHITELIST_ACTION_CONTINUE.
   * Field introduced in 18.2.3.
   * @return actions
   */
  @VsoMethod
  public List<String> getActions() {
    return actions;
  }

  /**
   * This is the setter method. this will set the actions
   * Actions generated by this rule.
   * Enum options - WAF_POLICY_WHITELIST_ACTION_ALLOW, WAF_POLICY_WHITELIST_ACTION_DETECTION_MODE, WAF_POLICY_WHITELIST_ACTION_CONTINUE.
   * Field introduced in 18.2.3.
   * @return actions
   */
  @VsoMethod
  public void setActions(List<String>  actions) {
    this.actions = actions;
  }

  /**
   * This is the setter method this will set the actions
   * Actions generated by this rule.
   * Enum options - WAF_POLICY_WHITELIST_ACTION_ALLOW, WAF_POLICY_WHITELIST_ACTION_DETECTION_MODE, WAF_POLICY_WHITELIST_ACTION_CONTINUE.
   * Field introduced in 18.2.3.
   * @return actions
   */
  @VsoMethod
  public WafWhitelistLog addActionsItem(String actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<String>();
    }
    this.actions.add(actionsItem);
    return this;
  }


  /**
   * This is the getter method this will return the attribute value.
   * Name of the matched rule.
   * Field introduced in 18.2.3.
   * @return ruleName
   */
  @VsoMethod
  public String getRuleName() {
    return ruleName;
  }

  /**
   * This is the setter method to the attribute.
   * Name of the matched rule.
   * Field introduced in 18.2.3.
   * @param ruleName set the ruleName.
   */
  @VsoMethod
  public void setRuleName(String  ruleName) {
    this.ruleName = ruleName;
  }



@Override
public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
  WafWhitelistLog objWafWhitelistLog = (WafWhitelistLog) o;
  return   Objects.equals(this.ruleName, objWafWhitelistLog.ruleName)&&
  Objects.equals(this.actions, objWafWhitelistLog.actions);
}

@Override
public String toString() {
  StringBuilder sb = new StringBuilder();
  sb.append("class WafWhitelistLog {\n");
      sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
        sb.append("    ruleName: ").append(toIndentedString(ruleName)).append("\n");
      sb.append("}");
  return sb.toString();
}

/**
* Convert the given object to string with each line indented by 4 spaces
* (except the first line).
*/
private String toIndentedString(java.lang.Object o) {
  if (o == null) {
    return "null";
  }
  return o.toString().replace("\n", "\n    ");
}
}
